local factory=dofile('Scripts/wheel_routing.lua')
local route=factory()
route:Configure({InteractionMode=0,PrimaryWheel=1})
assert(route.active=='Ability')
assert(route:Phase({group='Ability',slot=1},'Triggered'))
assert(not route:Phase({group='Ability',slot=1},'Started'))

route:Configure({InteractionMode=1,PrimaryWheel=0})
assert(route.active=='Consumable')
local dispatch,changed=route:Phase({select='secondary',momentary=true},'Started')
assert(not dispatch and changed and route.active=='Ability')
dispatch,changed=route:Phase({select='secondary',momentary=true},'Triggered')
assert(not dispatch and not changed and route.active=='Ability')
dispatch,changed=route:Phase({select='secondary',momentary=true},'Completed')
assert(not dispatch and changed and route.active=='Consumable')
route:Phase({select='secondary',momentary=true},'Started')
route:Phase({select='secondary',momentary=true},'Canceled')
assert(route.active=='Consumable','cancel returns momentary selection to Primary')

route:Phase({select='secondary'},'Started')
assert(route.active=='Consumable','Tap selection ignores Started')
route:Phase({select='secondary'},'Triggered')
assert(route.active=='Ability')
route:Phase({select='primary'},'Triggered')
assert(route.active=='Consumable')
route:Reset();assert(route.active=='Consumable')
assert(not pcall(function()route:Configure({InteractionMode=2})end))
print('PASS Independent dispatch and Selective Tap/raw Hold wheel routing')
